version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  static-code-analysis:
    jobs:
      - lint
  build:
    jobs:
      - build
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
